apiVersion: v1
kind: Namespace
metadata:
  name: cluster-api
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: byoi-management-server-cluster
  namespace: cluster-api
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: byoi-management-server-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: byoi-management-server-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: byoi-management-server-control-plane
  namespace: cluster-api
spec:
  additionalTags:
    author: Tim Tsoi
  endpointAccess:
    private: true
    public: true
    publicCIDRs:
      - 0.0.0.0/0
  eksClusterName: byoi-cluster-api-management-server
  iamAuthenticatorConfig:
    mapRoles:
      - groups:
          - system:bootstrappers
          - system:nodes
        rolearn: arn:aws:iam::{specify your AWS account ID}:role/nodes.cluster-api-provider-aws.sigs.k8s.io
        username: system:node:{{EC2PrivateDNSName}}
  network:
    subnets:
      - id: subnet-***
      - id: subnet-***
      - id: subnet-***
    vpc:
      id: vpc-***
  logging:
    apiServer: true
    audit: true
    authenticator: true
    controllerManager: true
    scheduler: true
  region: ap-southeast-1
  sshKeyName: cluster-api
  version: v1.21
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  name: byoi-cluster-api-management-server-managed-nodegroup-template
  namespace: cluster-api
spec:
  additionalTags:
    author: Tim Tsoi
  amiType: AL2_x86_64
  capacityType: onDemand
  diskSize: 30
  eksNodegroupName: byoi-cluster-api-management-server-nodegroup
  labels:
    author: Tim-Tsoi
    description: this-is-a-k8s-label
  instanceType: t3.medium
  subnetIDs:
    - subnet-***
    - subnet-***
    - subnet-***
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: byoi-cluster-api-management-server-managed-nodegroup
  namespace: cluster-api
spec:
  clusterName: byoi-management-server-cluster
  replicas: 3
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: byoi-cluster-api-management-server
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSManagedMachinePool
        name: byoi-cluster-api-management-server-managed-nodegroup-template
