apiVersion: v1
kind: Namespace
metadata:
  name: capi
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: managed-mgnt-cl
  namespace: capi
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: managed-mgnt-cl
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: managed-mgnt-cl
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: managed-mgnt-cl
  namespace: capi
spec:
  additionalTags:
    author: Tim Tsoi
  endpointAccess:
    private: true
    public: true
    publicCIDRs:
      - 0.0.0.0/0
  eksClusterName: managed-mgnt-cl
  iamAuthenticatorConfig:
    mapUsers:
      - groups:
          - system:masters
        userarn: arn:aws:iam::******************:root
        username: admin
  logging:
    apiServer: true
    audit: true
    authenticator: true
    controllerManager: true
    scheduler: true
  region: ap-southeast-1
  roleName: eks-controlplane.cluster-api-provider-aws.sigs.k8s.io
  version: v1.21
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  name: eks-mg-al2-t3-med-30-managed-mgnt-cl
  namespace: capi
spec:
  additionalTags:
    author: Tim Tsoi
  amiType: AL2_x86_64
  capacityType: onDemand
  diskSize: 30
  eksNodegroupName: eks-mg-al2-t3-med-30-managed-mgnt-cl
  labels:
    author: Tim-Tsoi
    description: this-is-a-k8s-label
  instanceType: t3.medium
  roleName: nodes.cluster-api-provider-aws.sigs.k8s.io
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: eks-mg-al2-t3-med-30-managed-mgnt-cl
  namespace: capi
spec:
  clusterName: managed-mgnt-cl
  replicas: 3
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: managed-mgnt-cl
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSManagedMachinePool
        name: eks-mg-al2-t3-med-30-managed-mgnt-cl
